spring:
  application:
    name: tripplanner
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: devpass
  jpa:
    hibernate:
      ddl-auto: validate

ors:
  api-key: ${eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImZkOGFhNjc5MzUwMDRiOTZhZjI0NDU3MmJkM2NlNzVkIiwiaCI6Im11cm11cjY0In0=}